import { Listing, Category } from './types'

export const CATEGORIES: { id: Category; name: string; description: string }[] = [
  {
    id: 'cars',
    name: 'Cars',
    description: 'Browse our selection of automobiles'
  },
  {
    id: 'motorcycles',
    name: 'Motorcycles',
    description: 'Find your perfect bike'
  },
  {
    id: 'trucks',
    name: 'Trucks',
    description: 'Heavy duty and commercial vehicles'
  },
  {
    id: 'rvs',
    name: 'RVs & Campers',
    description: 'Recreational vehicles and motorhomes'
  },
  {
    id: 'parts',
    name: 'Parts & Accessories',
    description: 'Auto parts and accessories'
  }
]

export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: 'car-1',
    userId: 'seller-1',
    category: 'cars',
    status: 'active',
    title: '2023 Tesla Model S Plaid',
    description: 'Tri-motor all-wheel drive with 1,020 horsepower. Autopilot, premium interior, carbon fiber spoiler, 19" Tempest wheels. Factory warranty remaining. Immaculate condition with full service history.',
    price: 89900,
    location: 'Palo Alto, CA',
    images: ['https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format'],
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
    views: 456,
    isFeatured: true,
    brand: 'Tesla',
    model: 'Model S',
    year: 2023,
    mileage: 8500,
    fuelType: 'Electric',
    transmission: 'Automatic',
    condition: 'used',
    bodyType: 'Sedan',
    color: 'Midnight Silver Metallic',
    historyReportAvailable: true,
    warrantyIncluded: true,
    deliveryAvailable: true
  },
  {
    id: 'car-2',
    userId: 'seller-2',
    category: 'cars',
    status: 'active',
    title: '2024 Porsche 911 Carrera S',
    description: 'Brand new 443hp twin-turbo flat-six engine, Sport Chrono package, PASM suspension, premium leather interior, Burmester sound system. Zero miles, full factory warranty.',
    price: 127900,
    location: 'Miami, FL',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format'],
    createdAt: '2024-01-19T14:30:00Z',
    updatedAt: '2024-01-19T14:30:00Z',
    views: 789,
    isFeatured: true,
    brand: 'Porsche',
    model: '911',
    year: 2024,
    mileage: 12,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'new',
    bodyType: 'Coupe',
    engineSize: '3.0L H6',
    color: 'Guards Red',
    warrantyIncluded: true,
    deliveryAvailable: true
  },
  {
    id: 'car-3',
    userId: 'seller-1',
    category: 'cars',
    status: 'active',
    title: '2022 BMW M3 Competition xDrive',
    description: 'Twin-turbo inline-6 with 503hp, M carbon ceramic brakes, carbon fiber roof, Merino leather, Harman Kardon sound. One owner, meticulously maintained.',
    price: 72500,
    location: 'Los Angeles, CA',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format'],
    createdAt: '2024-01-18T09:15:00Z',
    updatedAt: '2024-01-18T09:15:00Z',
    views: 523,
    isFeatured: true,
    brand: 'BMW',
    model: 'M3',
    year: 2022,
    mileage: 12800,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'used',
    bodyType: 'Sedan',
    engineSize: '3.0L I6',
    color: 'Isle of Man Green',
    historyReportAvailable: true,
    warrantyIncluded: true
  },
  {
    id: 'car-4',
    userId: 'seller-3',
    category: 'cars',
    status: 'active',
    title: '2023 Mercedes-AMG GT 63 S',
    description: 'Four-door coupe with 630hp V8 biturbo, AMG Performance 4MATIC+, AMG Ride Control+ suspension, Burmester 3D sound, Nappa leather. Like new condition.',
    price: 149900,
    location: 'New York, NY',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format'],
    createdAt: '2024-01-17T16:45:00Z',
    updatedAt: '2024-01-17T16:45:00Z',
    views: 612,
    isFeatured: true,
    brand: 'Mercedes-Benz',
    model: 'AMG GT',
    year: 2023,
    mileage: 5200,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'certified',
    bodyType: 'Sedan',
    engineSize: '4.0L V8',
    color: 'Obsidian Black',
    historyReportAvailable: true,
    warrantyIncluded: true,
    deliveryAvailable: true
  },
  {
    id: 'car-5',
    userId: 'seller-2',
    category: 'cars',
    status: 'active',
    title: '2021 Audi RS6 Avant',
    description: 'Twin-turbo V8 wagon with 591hp, Quattro AWD, adaptive air suspension, Bang & Olufsen sound, carbon fiber trim. Perfect blend of performance and practicality.',
    price: 94900,
    location: 'Seattle, WA',
    images: ['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&auto=format'],
    createdAt: '2024-01-16T11:20:00Z',
    updatedAt: '2024-01-16T11:20:00Z',
    views: 445,
    brand: 'Audi',
    model: 'RS6',
    year: 2021,
    mileage: 18500,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'used',
    bodyType: 'Wagon',
    engineSize: '4.0L V8',
    color: 'Nardo Gray',
    historyReportAvailable: true,
    deliveryAvailable: true
  },
  {
    id: 'car-6',
    userId: 'seller-3',
    category: 'cars',
    status: 'active',
    title: '2024 Lexus LC 500 Convertible',
    description: 'Naturally aspirated 5.0L V8 with 471hp, Mark Levinson sound, semi-aniline leather, adaptive suspension. Brand new, showroom condition.',
    price: 104900,
    location: 'Dallas, TX',
    images: ['https://images.unsplash.com/photo-1555353540-64580f50da8e?w=800&auto=format'],
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
    views: 378,
    brand: 'Lexus',
    model: 'LC 500',
    year: 2024,
    mileage: 45,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'new',
    bodyType: 'Convertible',
    engineSize: '5.0L V8',
    color: 'Structural Blue',
    warrantyIncluded: true,
    deliveryAvailable: true
  },
  {
    id: 'car-7',
    userId: 'seller-1',
    category: 'cars',
    status: 'active',
    title: '2023 Chevrolet Corvette Z06',
    description: 'Flat-plane crank V8 producing 670hp, carbon fiber wheels, Magnetic Ride Control 4.0, Competition Sport seats. Track-ready supercar.',
    price: 119900,
    location: 'Austin, TX',
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format'],
    createdAt: '2024-01-14T13:25:00Z',
    updatedAt: '2024-01-14T13:25:00Z',
    views: 698,
    isFeatured: true,
    brand: 'Chevrolet',
    model: 'Corvette',
    year: 2023,
    mileage: 1200,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'used',
    bodyType: 'Coupe',
    engineSize: '5.5L V8',
    color: 'Rapid Blue',
    historyReportAvailable: true,
    warrantyIncluded: true
  },
  {
    id: 'car-8',
    userId: 'seller-2',
    category: 'cars',
    status: 'active',
    title: '2022 Range Rover Sport SVR',
    description: 'Supercharged V8 with 575hp, adaptive air suspension, Meridian signature sound, Windsor leather, carbon fiber package. Luxury meets performance.',
    price: 98500,
    location: 'Denver, CO',
    images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format'],
    createdAt: '2024-01-13T10:40:00Z',
    updatedAt: '2024-01-13T10:40:00Z',
    views: 412,
    brand: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2022,
    mileage: 14200,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'used',
    bodyType: 'SUV',
    engineSize: '5.0L V8',
    color: 'Santorini Black',
    historyReportAvailable: true,
    warrantyIncluded: true
  },
  {
    id: 'car-9',
    userId: 'seller-3',
    category: 'cars',
    status: 'active',
    title: '2024 Toyota GR Supra 3.0 Premium',
    description: 'Turbocharged inline-6 with 382hp, adaptive suspension, JBL premium audio, alcantara-wrapped steering wheel. Brand new with full warranty.',
    price: 57900,
    location: 'Phoenix, AZ',
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&auto=format'],
    createdAt: '2024-01-12T15:50:00Z',
    updatedAt: '2024-01-12T15:50:00Z',
    views: 534,
    brand: 'Toyota',
    model: 'GR Supra',
    year: 2024,
    mileage: 8,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'new',
    bodyType: 'Coupe',
    engineSize: '3.0L I6',
    color: 'Nitro Yellow',
    warrantyIncluded: true,
    deliveryAvailable: true
  },
  {
    id: 'car-10',
    userId: 'seller-1',
    category: 'cars',
    status: 'active',
    title: '2021 Maserati Levante Trofeo',
    description: 'Twin-turbo Ferrari-built V8 with 580hp, Skyhook air suspension, Bowers & Wilkins audio, Pieno Fiore leather. Italian luxury SUV.',
    price: 79900,
    location: 'Chicago, IL',
    images: ['https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=800&auto=format'],
    createdAt: '2024-01-11T09:30:00Z',
    updatedAt: '2024-01-11T09:30:00Z',
    views: 289,
    brand: 'Maserati',
    model: 'Levante',
    year: 2021,
    mileage: 22400,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'used',
    bodyType: 'SUV',
    engineSize: '3.8L V8',
    color: 'Blu Emozione',
    historyReportAvailable: true
  },
  {
    id: 'car-11',
    userId: 'seller-2',
    category: 'cars',
    status: 'active',
    title: '2023 Nissan GT-R Premium',
    description: 'Twin-turbo V6 with 565hp, ATTESA E-TS AWD system, Bose audio, Recaro seats. The ultimate daily supercar with incredible performance.',
    price: 119500,
    location: 'Atlanta, GA',
    images: ['https://images.unsplash.com/photo-1585844468315-48c72dd68e3a?w=800&auto=format'],
    createdAt: '2024-01-10T12:15:00Z',
    updatedAt: '2024-01-10T12:15:00Z',
    views: 645,
    isFeatured: true,
    brand: 'Nissan',
    model: 'GT-R',
    year: 2023,
    mileage: 4800,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'used',
    bodyType: 'Coupe',
    engineSize: '3.8L V6',
    color: 'Bayside Blue',
    historyReportAvailable: true,
    warrantyIncluded: true
  },
  {
    id: 'car-12',
    userId: 'seller-3',
    category: 'cars',
    status: 'active',
    title: '2024 Honda Civic Type R',
    description: 'Turbocharged 2.0L with 315hp, 6-speed manual, Brembo brakes, adaptive dampers. The pinnacle of hot hatchback performance.',
    price: 48900,
    location: 'Portland, OR',
    images: ['https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&auto=format'],
    createdAt: '2024-01-09T14:45:00Z',
    updatedAt: '2024-01-09T14:45:00Z',
    views: 478,
    brand: 'Honda',
    model: 'Civic Type R',
    year: 2024,
    mileage: 125,
    fuelType: 'Gasoline',
    transmission: 'Manual',
    condition: 'new',
    bodyType: 'Hatchback',
    engineSize: '2.0L I4',
    color: 'Championship White',
    warrantyIncluded: true
  },
  {
    id: 'moto-1',
    userId: 'seller-4',
    category: 'motorcycles',
    status: 'active',
    title: '2023 Ducati Panigale V4 SP2',
    description: 'Limited edition superbike with 215hp, carbon fiber wings, Öhlins Smart EC 2.0 suspension, Brembo Stylema calipers. Track-proven performance.',
    price: 39900,
    location: 'Las Vegas, NV',
    images: ['https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&auto=format'],
    createdAt: '2024-01-19T11:00:00Z',
    updatedAt: '2024-01-19T11:00:00Z',
    views: 567,
    isFeatured: true,
    brand: 'Ducati',
    model: 'Panigale V4',
    year: 2023,
    mileage: 1200,
    fuelType: 'Gasoline',
    transmission: 'Manual',
    condition: 'used',
    engineSize: '1103cc',
    color: 'Winter Test Livery',
    warrantyIncluded: true
  },
  {
    id: 'moto-2',
    userId: 'seller-4',
    category: 'motorcycles',
    status: 'active',
    title: '2024 BMW S 1000 RR M Sport',
    description: 'Race-ready 205hp inline-4, M carbon wheels, M GPS lap timer, DDC Pro suspension, HP Race calibration. The ultimate track weapon.',
    price: 32900,
    location: 'San Diego, CA',
    images: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&auto=format'],
    createdAt: '2024-01-18T10:20:00Z',
    updatedAt: '2024-01-18T10:20:00Z',
    views: 423,
    brand: 'BMW',
    model: 'S 1000 RR',
    year: 2024,
    mileage: 45,
    fuelType: 'Gasoline',
    transmission: 'Manual',
    condition: 'new',
    engineSize: '999cc',
    color: 'M Motorsport',
    warrantyIncluded: true
  },
  {
    id: 'moto-3',
    userId: 'seller-5',
    category: 'motorcycles',
    status: 'active',
    title: '2023 Kawasaki Ninja H2 SX SE',
    description: 'Supercharged sport-tourer with 200hp, electronic suspension, cornering ABS, TFT display, Brembo brakes. Supercharged perfection.',
    price: 27500,
    location: 'Houston, TX',
    images: ['https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&auto=format'],
    createdAt: '2024-01-17T09:35:00Z',
    updatedAt: '2024-01-17T09:35:00Z',
    views: 356,
    brand: 'Kawasaki',
    model: 'Ninja H2',
    year: 2023,
    mileage: 3400,
    fuelType: 'Gasoline',
    transmission: 'Manual',
    condition: 'used',
    engineSize: '998cc',
    color: 'Emerald Blazed Green',
    historyReportAvailable: true
  },
  {
    id: 'moto-4',
    userId: 'seller-4',
    category: 'motorcycles',
    status: 'active',
    title: '2024 Harley-Davidson Road Glide ST',
    description: 'Milwaukee-Eight 117 V-twin, RDRS cornering technology, Rockford Fosgate audio, adaptive ride height. Ultimate touring machine.',
    price: 34900,
    location: 'Milwaukee, WI',
    images: ['https://images.unsplash.com/photo-1558980664-769d59546b3d?w=800&auto=format'],
    createdAt: '2024-01-16T13:50:00Z',
    updatedAt: '2024-01-16T13:50:00Z',
    views: 289,
    brand: 'Harley-Davidson',
    model: 'Road Glide',
    year: 2024,
    mileage: 220,
    fuelType: 'Gasoline',
    transmission: 'Manual',
    condition: 'new',
    engineSize: '1923cc',
    color: 'Vivid Black',
    warrantyIncluded: true
  },
  {
    id: 'moto-5',
    userId: 'seller-5',
    category: 'motorcycles',
    status: 'active',
    title: '2023 Yamaha MT-10 SP',
    description: 'Crossplane 998cc inline-4 with 165hp, Öhlins electronic suspension, carbon fiber bodywork, quick shifter. Hyper-naked performance.',
    price: 16900,
    location: 'San Francisco, CA',
    images: ['https://images.unsplash.com/photo-1571800122318-7ce0c1d5b085?w=800&auto=format'],
    createdAt: '2024-01-15T11:15:00Z',
    updatedAt: '2024-01-15T11:15:00Z',
    views: 412,
    brand: 'Yamaha',
    model: 'MT-10',
    year: 2023,
    mileage: 2800,
    fuelType: 'Gasoline',
    transmission: 'Manual',
    condition: 'used',
    engineSize: '998cc',
    color: 'Icon Blue',
    historyReportAvailable: true
  },
  {
    id: 'moto-6',
    userId: 'seller-4',
    category: 'motorcycles',
    status: 'active',
    title: '2024 Triumph Speed Triple 1200 RR',
    description: 'Triple-cylinder 177hp engine, Öhlins NIX30 forks, Brembo Stylema brakes, carbon fiber bodywork. British engineering at its finest.',
    price: 21900,
    location: 'Boston, MA',
    images: ['https://images.unsplash.com/photo-1591117207239-788bf8de6c3b?w=800&auto=format'],
    createdAt: '2024-01-14T08:40:00Z',
    updatedAt: '2024-01-14T08:40:00Z',
    views: 378,
    brand: 'Triumph',
    model: 'Speed Triple',
    year: 2024,
    mileage: 95,
    fuelType: 'Gasoline',
    transmission: 'Manual',
    condition: 'new',
    engineSize: '1160cc',
    color: 'Matte Storm Grey',
    warrantyIncluded: true
  },
  {
    id: 'truck-1',
    userId: 'seller-6',
    category: 'trucks',
    status: 'active',
    title: '2024 Ford F-150 Raptor R',
    description: 'Supercharged 5.2L V8 with 700hp, Fox Live Valve shocks, 37" BFGoodrich tires, Recaro seats, torque-on-demand transfer case. Desert domination.',
    price: 109900,
    location: 'Phoenix, AZ',
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format'],
    createdAt: '2024-01-19T10:25:00Z',
    updatedAt: '2024-01-19T10:25:00Z',
    views: 723,
    isFeatured: true,
    brand: 'Ford',
    model: 'F-150 Raptor R',
    year: 2024,
    mileage: 340,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'new',
    bodyType: 'Pickup',
    engineSize: '5.2L V8',
    color: 'Code Orange',
    warrantyIncluded: true,
    deliveryAvailable: true
  },
  {
    id: 'truck-2',
    userId: 'seller-6',
    category: 'trucks',
    status: 'active',
    title: '2023 RAM 1500 TRX',
    description: 'Supercharged 6.2L HEMI V8 with 702hp, Bilstein adaptive suspension, 35" Goodyear tires, leather interior. The most powerful production truck.',
    price: 89900,
    location: 'Dallas, TX',
    images: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&auto=format'],
    createdAt: '2024-01-18T14:15:00Z',
    updatedAt: '2024-01-18T14:15:00Z',
    views: 612,
    isFeatured: true,
    brand: 'RAM',
    model: '1500 TRX',
    year: 2023,
    mileage: 6800,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'used',
    bodyType: 'Pickup',
    engineSize: '6.2L V8',
    color: 'Ignition Orange',
    historyReportAvailable: true,
    warrantyIncluded: true
  },
  {
    id: 'truck-3',
    userId: 'seller-7',
    category: 'trucks',
    status: 'active',
    title: '2024 Chevrolet Silverado ZR2 Bison',
    description: 'Off-road package with Multimatic DSSV shocks, 35" mud-terrain tires, locking diffs, AEV front bumper. Built for extreme terrain.',
    price: 74900,
    location: 'Denver, CO',
    images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&auto=format'],
    createdAt: '2024-01-17T09:50:00Z',
    updatedAt: '2024-01-17T09:50:00Z',
    views: 445,
    brand: 'Chevrolet',
    model: 'Silverado ZR2',
    year: 2024,
    mileage: 180,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'new',
    bodyType: 'Pickup',
    engineSize: '6.2L V8',
    color: 'Red Hot',
    warrantyIncluded: true
  },
  {
    id: 'truck-4',
    userId: 'seller-6',
    category: 'trucks',
    status: 'active',
    title: '2023 Toyota Tundra TRD Pro',
    description: 'Twin-turbo V6 hybrid with 437hp, FOX suspension, JBL audio, panoramic moonroof, multi-terrain select. Legendary reliability meets performance.',
    price: 67900,
    location: 'Seattle, WA',
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format'],
    createdAt: '2024-01-16T11:30:00Z',
    updatedAt: '2024-01-16T11:30:00Z',
    views: 534,
    brand: 'Toyota',
    model: 'Tundra',
    year: 2023,
    mileage: 8900,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    condition: 'used',
    bodyType: 'Pickup',
    engineSize: '3.5L V6',
    color: 'Solar Octane',
    historyReportAvailable: true,
    warrantyIncluded: true
  },
  {
    id: 'truck-5',
    userId: 'seller-7',
    category: 'trucks',
    status: 'active',
    title: '2024 GMC Sierra 1500 Denali Ultimate',
    description: 'Premium luxury truck with 6.2L V8, adaptive air suspension, Super Cruise, 15" head-up display, massage seats. Ultimate refinement.',
    price: 82900,
    location: 'Atlanta, GA',
    images: ['https://images.unsplash.com/photo-1615906655593-ad0386982a0f?w=800&auto=format'],
    createdAt: '2024-01-15T10:45:00Z',
    updatedAt: '2024-01-15T10:45:00Z',
    views: 389,
    brand: 'GMC',
    model: 'Sierra Denali',
    year: 2024,
    mileage: 425,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    condition: 'new',
    bodyType: 'Pickup',
    engineSize: '6.2L V8',
    color: 'Onyx Black',
    warrantyIncluded: true,
    deliveryAvailable: true
  },
  {
    id: 'rv-1',
    userId: 'seller-8',
    category: 'rvs',
    status: 'active',
    title: '2024 Airstream Classic 33FB Twin',
    description: 'Luxury travel trailer with dual queen beds, full kitchen with residential fridge, wet bath, solar panels, smart RV technology. Iconic aluminum design.',
    price: 189900,
    location: 'Portland, OR',
    images: ['https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=800&auto=format'],
    createdAt: '2024-01-19T09:20:00Z',
    updatedAt: '2024-01-19T09:20:00Z',
    views: 456,
    isFeatured: true,
    brand: 'Airstream',
    model: 'Classic',
    year: 2024,
    mileage: 120,
    condition: 'new',
    color: 'Polished Aluminum',
    warrantyIncluded: true,
    deliveryAvailable: true
  },
  {
    id: 'rv-2',
    userId: 'seller-8',
    category: 'rvs',
    status: 'active',
    title: '2023 Winnebago Revel 44E',
    description: '4x4 Mercedes-Benz Sprinter chassis, Truma Combi Eco heating, power lift bed, wet bath, 200W solar, perfect for boondocking adventures.',
    price: 219900,
    location: 'Denver, CO',
    images: ['https://images.unsplash.com/photo-1464219789935-c2d9d9aba644?w=800&auto=format'],
    createdAt: '2024-01-18T13:40:00Z',
    updatedAt: '2024-01-18T13:40:00Z',
    views: 523,
    brand: 'Winnebago',
    model: 'Revel',
    year: 2023,
    mileage: 4200,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    condition: 'used',
    color: 'Graphite Metallic',
    historyReportAvailable: true,
    warrantyIncluded: true
  },
  {
    id: 'rv-3',
    userId: 'seller-9',
    category: 'rvs',
    status: 'active',
    title: '2024 Thor Aria 3901',
    description: 'Luxury diesel pusher with Cummins 380hp, king bed, dual recliners, residential fridge, washer/dryer, fireplace. Home-level comfort.',
    price: 425000,
    location: 'Phoenix, AZ',
    images: ['https://images.unsplash.com/photo-1543395136-75845d5f43de?w=800&auto=format'],
    createdAt: '2024-01-17T11:15:00Z',
    updatedAt: '2024-01-17T11:15:00Z',
    views: 612,
    brand: 'Thor',
    model: 'Aria',
    year: 2024,
    mileage: 280,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    condition: 'new',
    color: 'Champagne',
    warrantyIncluded: true,
    deliveryAvailable: true
  },
  {
    id: 'rv-4',
    userId: 'seller-8',
    category: 'rvs',
    status: 'active',
    title: '2023 Forest River Rockwood Geo Pro 19FBS',
    description: 'Lightweight travel trailer perfect for small tow vehicles. Queen bed, full kitchen, wet bath, Murphy bed. Only 3,485 lbs dry weight.',
    price: 32900,
    location: 'Boise, ID',
    images: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&auto=format'],
    createdAt: '2024-01-16T10:30:00Z',
    updatedAt: '2024-01-16T10:30:00Z',
    views: 378,
    brand: 'Forest River',
    model: 'Rockwood Geo Pro',
    year: 2023,
    mileage: 2100,
    condition: 'used',
    color: 'Pewter',
    historyReportAvailable: true
  },
  {
    id: 'parts-1',
    userId: 'seller-10',
    category: 'parts',
    status: 'active',
    title: 'Akrapovič Evolution Titanium Exhaust - BMW M3/M4',
    description: 'Complete titanium exhaust system with carbon fiber tips. Reduces weight by 18 lbs, increases power and sound. Includes installation hardware.',
    price: 6490,
    location: 'Los Angeles, CA',
    images: ['https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&auto=format'],
    createdAt: '2024-01-19T08:15:00Z',
    updatedAt: '2024-01-19T08:15:00Z',
    views: 234,
    partType: 'Exhaust',
    partCondition: 'new',
    compatibility: 'BMW M3/M4 F80/F82/F83',
    brand: 'Akrapovič'
  },
  {
    id: 'parts-2',
    userId: 'seller-10',
    category: 'parts',
    status: 'active',
    title: 'Brembo GT-R Big Brake Kit - Front 380mm',
    description: '6-piston monobloc calipers, 380mm slotted rotors, high-performance pads. Direct bolt-on upgrade. Red, yellow, or black calipers available.',
    price: 3850,
    location: 'Miami, FL',
    images: ['https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=800&auto=format'],
    createdAt: '2024-01-18T12:20:00Z',
    updatedAt: '2024-01-18T12:20:00Z',
    views: 312,
    partType: 'Brakes',
    partCondition: 'new',
    compatibility: 'Multiple Applications',
    brand: 'Brembo'
  },
  {
    id: 'parts-3',
    userId: 'seller-11',
    category: 'parts',
    status: 'active',
    title: 'KW V3 Coilover Suspension Kit',
    description: 'Adjustable rebound and compression damping, stainless steel construction, TÜV approved. Perfect for street and occasional track use.',
    price: 2995,
    location: 'Seattle, WA',
    images: ['https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&auto=format'],
    createdAt: '2024-01-17T14:45:00Z',
    updatedAt: '2024-01-17T14:45:00Z',
    views: 267,
    partType: 'Suspension',
    partCondition: 'new',
    compatibility: 'Porsche 911 991',
    brand: 'KW'
  },
  {
    id: 'parts-4',
    userId: 'seller-10',
    category: 'parts',
    status: 'active',
    title: 'Eventuri Carbon Fiber Intake System',
    description: 'True carbon fiber airbox with Kevlar weave, dyno-proven +15hp gains, amazing induction sound. Complete plug-and-play installation.',
    price: 1450,
    location: 'Austin, TX',
    images: ['https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&auto=format'],
    createdAt: '2024-01-16T09:30:00Z',
    updatedAt: '2024-01-16T09:30:00Z',
    views: 389,
    partType: 'Intake',
    partCondition: 'new',
    compatibility: 'BMW M2/M3/M4 S55',
    brand: 'Eventuri'
  },
  {
    id: 'parts-5',
    userId: 'seller-11',
    category: 'parts',
    status: 'active',
    title: 'HRE P101 Forged Wheels 20" Set of 4',
    description: 'Monoblock forged aluminum wheels, 20x9 front / 20x11 rear, custom finish options. Includes center caps and hardware. Weight: 19 lbs each.',
    price: 8900,
    location: 'San Diego, CA',
    images: ['https://images.unsplash.com/photo-1563459802257-4426c78c5a2e?w=800&auto=format'],
    createdAt: '2024-01-15T11:50:00Z',
    updatedAt: '2024-01-15T11:50:00Z',
    views: 456,
    partType: 'Wheels',
    partCondition: 'new',
    compatibility: 'Multiple Fitments',
    brand: 'HRE'
  }
]

export const BRANDS_BY_CATEGORY: Record<Category, string[]> = {
  cars: ['Acura', 'Audi', 'BMW', 'Chevrolet', 'Ford', 'Honda', 'Hyundai', 'Lexus', 'Mercedes-Benz', 'Nissan', 'Porsche', 'Tesla', 'Toyota', 'Volkswagen'],
  motorcycles: ['BMW', 'Ducati', 'Harley-Davidson', 'Honda', 'Kawasaki', 'KTM', 'Suzuki', 'Triumph', 'Yamaha'],
  trucks: ['Chevrolet', 'Dodge', 'Ford', 'GMC', 'RAM', 'Toyota'],
  rvs: ['Airstream', 'Forest River', 'Jayco', 'Thor', 'Winnebago'],
  parts: ['ACDelco', 'Bosch', 'Denso', 'OEM', 'Performance', 'Universal']
}

export const FUEL_TYPES = ['Gasoline', 'Diesel', 'Electric', 'Hybrid', 'Plug-in Hybrid']
export const TRANSMISSIONS = ['Automatic', 'Manual', 'CVT', 'Semi-Automatic']
export const CONDITIONS = ['New', 'Used', 'Certified Pre-Owned']
export const BODY_TYPES = ['Sedan', 'SUV', 'Coupe', 'Convertible', 'Wagon', 'Hatchback', 'Pickup', 'Van']

export const MOCK_VEHICLES: any[] = []
export const MOCK_ANNOUNCEMENTS: any[] = []
